commerce/auctions/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("create_listing", views.create_listing, name="create_listing"),
    path("<int:auction_id>", views.listing_page, name="listing_page"),


]

commerce/commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

commerce/auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    pass


class Auction(models.Model):

    # Categories
    MOTORS = "MOT"
    FASHION = "FAS"
    ELECTRONICS = "ELE"
    ARTS = "ART"
    HOME_GOODS = "HOM"
    SPORTING_GOODS = "SPO"
    TOYS = "TOY"
    STATIONARY = "STA"
    MUSIC = "MUS"

    CATEGORY = [
        (MOTORS, "Motors"),
        (FASHION, "Fashion"),
        (ELECTRONICS, "Electronics"),
        (ARTS, "Art"),
        (HOME_GOODS, "Home Goods"),
        (SPORTING_GOODS, "Sporting Goods"),
        (TOYS, "Toys"),
        (STATIONARY, "Stationary"),
        (MUSIC, "Music"),
        ]

    # Model fields
    # auto: auction_id
    seller = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=64, blank=False)
    description = models.TextField(blank=True)
    current_price = models.DecimalField(max_digits=11, decimal_places=2, default=0.0)
    category = models.CharField(max_length=3, choices=CATEGORY, default=MOTORS)
    image_url = models.URLField(blank=True)
    publication_date = models.DateTimeField(auto_now_add=True)
    closed = models.BooleanField(default=False)

    class Meta:
        verbose_name = "auction"
        verbose_name_plural = "auctions"

    def __str__(self):
        return f"Auction id: {self.id}, title: {self.title}, seller: {self.seller}"

class Bid(models.Model):

    # auto: bid_id
    auction = models.ForeignKey(Auction, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    bid_date = models.DateTimeField(auto_now_add=True)
    bid_price = models.DecimalField(max_digits=11, decimal_places=2)

    class Meta:
        verbose_name = "bid"
        verbose_name_plural = "bids"

    def __str__(self):
        return f"{self.user} bid {self.bid_price} $ on {self.auction}"


class Comment(models.Model):
    # Model fields
    # auto: comment_id
    auction = models.ForeignKey(Auction, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField(blank=False)
    comment_date = models.DateTimeField(auto_now_add=True, null=True)
    class Meta:
        verbose_name = "comment"
        verbose_name_plural = "comments"

    def __str__(self):
        return f"Comment {self.id} on auction {self.auction} made by {self.user}"

commerce/auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django import forms
from .models import User, Auction, Bid, Comment

#Class
class CreateListingForm(forms.ModelForm):
    """Creates form for Auction model."""

    title = forms.CharField(label="Title", max_length=20, required=True, widget=forms.TextInput(attrs={
        "autocomplete": "off",
        'placeholder': "Product Title",
        "aria-label": "title",
        "class": "form-control"
        }))

    description = forms.CharField(label="Description", widget=forms.Textarea(attrs={
        'placeholder': "Tell more about the product",
        'aria-label': "description",
        "class": "form-control"
        }))
    image_url = forms.URLField(label="Image URL", required=True, widget=forms.URLInput(attrs={
        "class": "form-control"
        }))

    category = forms.ChoiceField(required=True, choices=Auction.CATEGORY, widget=forms.Select(attrs={
        "class": "form-control"
        }))

    class Meta:
        model = Auction
        fields = ["title", "description", "category", "image_url"]


#Views
def index(request):
    return render(request, "auctions/index.html")


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "auctions/register.html")


@login_required(login_url="auctions:login")
def user_panel(request):
    """User Panel view: shows all auctions that user:
        * is currently selling
        * sold
        * is currently bidding
        * won
    """
    # Helpers
    all_distinct_bids =  Bid.objects.filter(user=request.user.id).values_list("auction", flat=True).distinct()
    won = []

    # Get auctions currently being sold by the user
    selling = Auction.objects.filter(closed=False, seller=request.user.id).order_by("-publication_date").all()

    # Get auction sold by the user
    sold = Auction.objects.filter(closed=True, seller=request.user.id).order_by("-publication_date").all()

    # Get auctions currently being bid by the user
    bidding = Auction.objects.filter(closed=False, id__in = all_distinct_bids).all()

    # Get auctions won by the user
    for auction in Auction.objects.filter(closed=True, id__in = all_distinct_bids).all():
        highest_bid = Bid.objects.filter(auction=auction.id).order_by('-bid_price').first()

        if highest_bid.user.id == request.user.id:
            won.append(auction)

    return render(request, "auctions/user_panel.html", {
        "selling": selling,
        "sold": sold,
        "bidding": bidding,
        "won": won
    })


@login_required(login_url="auctions:login")
def create_listing(request):
    """Create Listing view: allows to add new listing through a form."""
    if request.method == "POST":
        form = CreateListingForm(request.POST)
        if form.is_valid():
            # Get all data from the form
            title = form.cleaned_data["title"]
            description = form.cleaned_data["description"]
            category = form.cleaned_data["category"]
            image_url = form.cleaned_data["image_url"]

            # Save a record
            auction = Auction(
                seller = User.objects.get(pk=request.user.id),
                title = title,
                description = description,
                category = category,
                image_url = image_url
            )
            auction.save()
        else:
            return render(request, "auctions/create_listing.html", {
                "form": form
            })

    return render(request, "auctions/create_listing.html", {
        "form": CreateListingForm(),
    })

commerce/auctions/templates/auctions/create_listing.html
{% extends "auctions/layout.html" %}

{% block body %}

<div class="container">

    <div class="sub-title">Create Listing</div>
    <form action="{% url 'auctions:create_listing' %}", method="POST">
        {% csrf_token %}

        <div class="form-group mb-3">
            <label for="id_title">{{ form.title.label }}:</label>
            {{ form.title }}
        </div>

        <div class="form-group mb-3">
            <label for="id_description">{{ form.description.label }}:</label>
            {{ form.description }}
        </div>

        <div class="form-group mb-3">
            <label for="id_category">{{ form.category.label }}:</label>
            {{ form.category }}
        </div>

        <div class="form-group mb-3">
            <label for="id_image_url">{{ form.image_url.label }}:</label>
            {{ form.image_url }}
        </div>

        <button type="submit" class="btn btn-primary btn-new-blue" aria-label="submit">Submit</button>
    </form>
</div>
{% endblock %}

commerce/auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block body %}

    {% include "auctions/partials/listings_group.html" with auctions=auctions sub_title="All Listings"%}

{% endblock %}

commerce/auctions/templates/auctions/layout.html
{% load static %}

{% url 'auctions:index' as  index %}
{% url 'auctions:categories' category='MOT' as  motors %}
{% url 'auctions:categories' category='FAS' as  fashion %}
{% url 'auctions:categories' category='ELE' as  electronics %}
{% url 'auctions:categories' category='ART' as  art %}
{% url 'auctions:categories' category='HGA' as  home %}
{% url 'auctions:categories' category='SPO' as  sport %}
{% url 'auctions:categories' category='TOY' as  toys %}
{% url 'auctions:categories' category='BUS' as  business %}
{% url 'auctions:categories' category='MUS' as  music %}

<!DOCTYPE html>
<html lang="en">

    <head>
       <title>{% block title %}Auctions{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/7faee5c6e1.js" crossorigin="anonymous"></script>
    <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
    <link href="{% static 'auctions/sidebar.css' %}" rel="stylesheet">
    <script defer src="{% static 'auctions/sidebar.js' %}"></script>
    </head>

    <body>
        <h1>Auctions</h1>
        <div>
            {% if user.is_authenticated %}
                Signed in as <strong>{{ user.username }}</strong>.
            {% else %}
                Not signed in.
            {% endif %}
        </div>

        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'index' %}">Active Listings</a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'register' %}">Register</a>
                </li>
            {% endif %}
        </ul>
        <hr>
        {% block body %}
        {% endblock %}
    </body>
</html>

commerce/auctions/templates/auctions/listings_page.html
{% extends "auctions/layout.html" %}

{% block body %}
<div class="listing-page-main-btn">
    <!-- --- Watchlist button --- -->
    {% if user.is_authenticated and user.id != auction.seller.id %}
    <form action="{% url 'auctions:watchlist' %}" method="POST">
        {% csrf_token %}
        {% if on_watchlist %}
            <input type="submit" class="btn btn-danger" value="Remove from watchlist">
            <input type="hidden" name="on_watchlist" value="True">
        {% else %}
            <input type="submit" class="btn btn-success" value="Add to watchlist">
            <input type="hidden" name="on_watchlist" value="False">
        {% endif %}

        <input type="hidden" name="next" value="{{ request.path }}">
        <input type="hidden" name="auction_id" value="{{ auction.id }}">
    </form>
    {% endif %}
    <!-- --- Close auction button --- -->
    {% if user.id == auction.seller.id %}
        <form action="{% url 'auctions:close_auction' auction_id=auction.id %}" method="POST">
            {% csrf_token %}
            <input type="submit" class="btn btn-danger" value="Close auction" name="close_auction">
        </form>
    {% endif %}
</div>

<div class="auction-title">
    <h2>{{auction.title}}</h2>
</div>

<!-- --- Auction Description --- -->
<div class="card mb-3">
    {% if auction.image_url %}
        <div class="listing-page-img-wrapper m-4">
            <img src="{{ auction.image_url }}" class="card-img-top listing-page-img" alt="{{ auction.title }} photo">
        </div>
    {% endif %}

    <div class="card-body mb-3">
        <h4 class="card-title">Description:</h4>
        <p class="card-text">{{auction.description}}</p>
        <p class="card-text"><small class="text-muted">Created on: {{auction.publication_date}}</small></p>
    </div>

    <ul class="list-group list-group-flush">
        <div class="list-group-item">Current Price <strong>{{auction.current_price}} $ </strong></div>

        <!-- --- Bid info and form --- -->
        <div class="list-group-item text-muted">
            {% if bid_amount != 0 %}
                <small>{{ bid_amount }} bid(s) so far. {{ bid_message }}</small>
            {% else %}
                <small>No bids so far.</small>
            {% endif %}
        </div>
        {% if user.is_authenticated and user.id != auction.seller.id %}
            <form action="{% url 'auctions:bid' %}" method="POST" class="list-group-item">
                {% csrf_token %}
                <!-- <input type="number" name="bid" placeholder="Bid" step="0.01"> -->
                <div class="form-group row">
                    <div class="col-sm-10 col-8">
                        {{ bid_form }}
                    </div>
                    <input type="submit" value="Place Bid" class="btn btn-primary btn-new-blue col-sm-2 col-4">
                    <input type="hidden" name="next" value="{{ request.path }}">
                    <input type="hidden" name="auction_id" value="{{ auction.id }}">
                </div>
            </form>
        {% endif %}
    </ul>
</div>

<!-- --- Detail --- -->
<div class="card mb-3">
    <div class="card-body">
        <h4 class="card-title">Details</h4>
        <ul>
            <li>Seller: {{auction.seller.username}}</li>
            <li>Category: {{auction.get_category_display}}</li>
        </ul>
    </div>
</div>

<!-- --- Comments --- -->
<div class="card">
    <div class="card-body">
        <h4 class="card-title">Comments</h4>
        <p class="card-text">
            <div class="comment-section mb-4">
                {% for comment in comments %}
                    <div class="single-comment mb-3">
                        <div class="comment-text">
                            {{ comment.comment }}
                        </div>
                        <div class="comment-author">
                            ~ {{ comment.user.username }}
                        </div>
                        <small>{{ comment.comment_date }}</small>
                    </div>
                {% empty %}
                    <div class="no-comment">
                        No comments yet
                    </div>
                {% endfor %}
            </div>
            <form action="{% url 'auctions:handle_comment' auction_id=auction.id %}" method="POST">
                {% csrf_token %}
                <div class="mb-2">
                    {{ comment_form }}
                </div>
                <input type="submit" value="Comment" class="btn btn-primary btn-new-blue" style="float: right;">
            </form>
        </p>
    </div>
</div>
{% endblock %}

commerce/auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'register' %}">Register here.</a>

{% endblock %}

commerce/auctions/templates/auctions/partials/listing_layout.html
<div class="card auction-item mb-4 shadow">
    <a href="{% url 'auctions:listing_page' auction_id=auction.id %}">
    {% if auction.image_url %}
        <div class="card-image-wrapper">
            <img class="card-img-top listing-img" src="{{ auction.image_url }}" alt="{{ auction.title }} photo">
        </div>
    {% endif %}
        <div class="card-body">
            <h5 class="card-title"> {{ auction.title }} </h5>
            <div>
                <strong>Price:</strong> {{auction.current_price}} $
            </div>
            <div class="mb-2">
                <strong>Category:</strong> {{auction.get_category_display}}
            </div>
            <div class="auction-list-date">
                {{auction.publication_date}}
            </div>
        </div>
    </a>
</div>

commerce/auctions/templates/auctions/partials/listings_group.html
<div class="sub-title">
    {{ sub_title }}
</div>

<div class="container ">
    <div class="row row-cols-auto">
        {% for auction in auctions %}
            {% include "auctions/partials/listing_layout.html" %}
        {% empty %}
            No auctions yet.
        {% endfor %}
    </div>
</div>

commerce/auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'login' %}">Log In here.</a>

{% endblock %}